# This is the folder that contains the rule yaml files
# This can also be a list of directories
# Any .yaml file will be loaded as a rule
rules_folder: /etc/elastalert2/custom_rules

# How often ElastAlert will query Elasticsearch
# The unit can be anything from weeks to seconds
buffer_time:
  hours: 24
run_every:
  minutes: 1
# The Elasticsearch hostname for metadata writeback
# Note that every rule can have its own Elasticsearch host
es_host: elasticserverIP

# The Elasticsearch port
es_port: 9200
es_username: "username"
es_password: "jlkjlkjlkj"

ca_certs: /etc/elastalert2/http_ca.crt # copy elasticsearch crt

# Connect with TLS to Elasticsearch
use_ssl: True

# Verify TLS certificates
verify_certs: True

# Show TLS or certificate related warnings
ssl_show_warn: False


writeback_index: elastalert_status

alert_time_limit:
  days: 2

smtp_host: smtp-relay.brevo.com #free smtp server
smtp_port: 587
from_addr: youremail@mail.com
